### ISSUE TITLE
Video is freezing after two seconds of play

### ISSUE THREAD

**Issue by poorlostsoul** [HoyosIntegrity/V360-WebApp#1] opened 2018-11-30 12:33 UTC
I realized that it was easier to install node.js on a linux vm.  After after installing, I opened vlc and put in http://localhost:8059  the video played for 2 seconds and then froze for about a good 3-4 mins then repeated.  I am probably going to attack some more today.

**Comment by annerajb** [comment] 2018-11-30 14:08
Yeah noticed the same on Mac but not on Windows few weeks back. In Mac I
opened it in safari by pasting the link and noticed an significant improvement.
 It seems VLC in mac and Linux tries to buffer slowly each segment.

You can also try ffmpeg - ffmplay from Linux.

At first I was suspicious if it was due to the wifi connection. 
I went and enabled tethering on the localhost:8059 application website. 
Installed the mac drivers https://joshuawise.com/horndis#downloading_and_installing_horndis and configured a static IP address.
Ping responses improved dramatically (1ms) but it didn't make a difference on VLC dont recall if I tried Safari and USB I think I did and it had a 5 second delay. 

Can you paste the full m3u8 URL that you used?
If if contains a ip address or port that's not the one from the camera it will also have additional lag induced from the proxy running on server.js on port 8053.

I think I should modify the URL's generated to be direct to the camera to reduce this latency.

**Comment by annerajb** [comment] 2018-12-02 19:39
>Can you paste the full m3u8 URL that you used? If if contains a ip address or port that's not the one from the camera it will also have additional lag induced from the proxy running on server.js on port 8053. I think I should modify the URL's generated to be direct to the camera to reduce this latency.

I have verified the URL generated by the website is the direct IP to the camera bypassing the proxy server. 

After trying in USB connection and QuickTime in mac I manage to get it to stream the playlist without each segment buffering/stopping. 

Believe ffplay on Mac  also worked but didn't have video probably due to missing x11 on my end. But the debug log and audio seem to indicate it not stopping. (still a 5 second delay)

I need to try Ethernet via USB OTG. But I suspect all of the issues are now clientside. Since USB latency is 1ms. 
Later this week I want to try running VLC or ffplay directly inside the camera see if I can open the video 4 linux device directly and stream without using Miracast and Http live streaming.

**Comment by poorlostsoul** [comment] 2018-12-03 14:13
http://192.168.1.116/hls/973394849/hls.m3u8
here is the string I was using.  
Sorry I was out of pocket this weekend and friday...day to day work got in the way.

**Comment by annerajb** [comment] 2018-12-03 19:50
Ok so as I was guessing the issue is clientside:
I tried the following methods and have verified they work

1. Opening with Quicktime Version 10.5
2. Opening with ffmpeg version 4.1 and saving to an .mp4 file 
`ffmpeg -i http://192.168.0.1/hls/926397969/hls.m3u8 -acodec copy -bsf:a aac_adtstoasc -vcodec copy out.mp4`
3. mplayer version 1.3.0-4.2.1 http://192.168.0.1/hls/926397969/hls.m3u8

You can now use ffmpeg to stream the data to any format, or destination you want externally. 

Will see if I can find how to run it internally from the camera.

**Comment by annerajb** [comment] 2018-12-06 16:09
@poorlostsoul going to close this issue. 
Feel free to open a different one for any other item.

Got root access to the camera with a modified boot.img (changed the adbd binary) 
Also got a recent ffmpeg running inside of it (from 2.2 to 4.0 ) trying to get a direct read of the sensor/camera or find a way to pipe the recording to ffmpeg for streaming at their original resolution.

**Closed as completed by annerajb** 2018-12-06 16:09 UTC

**Comment by poorlostsoul** [comment] 2018-12-13 15:51
ok
